### ISSUE TITLE
stdlib MRE 6 simplifier

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5007]
```fortran
subroutine test_diag_int16()
integer, parameter :: n = 4
integer :: a(n, n), e(n,n)
e = diag1(diag(a))
contains
function diag(A) result(res)
integer, intent(in) :: A(:,:)
integer :: res(minval(shape(A)))
! integer :: i
! do i = 1, minval(shape(A))
!     res(i) = A(i,i)
! end do
end function diag

function diag1(v) result(res)
integer, intent(in) :: v(:)
integer :: res(size(v),size(v))
! integer :: i
! res = 0
! do i = 1, size(v)
!     res(i,i) = v(i)
! end do
end function diag1
end subroutine test_diag_int16

```

```console
% lfortran a.f90 --realloc-lhs --show-llvm
ASR verify pass error: FunctionCall::m_name diag must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2510, in main_app(int, char**)
    return emit_llvm(arg_file, lfortran_pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 940, in (anonymous namespace)::emit_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::PassManager&, LCompilers::CompilerOptions&)
    = fe.get_llvm(input, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 330, in LCompilers::FortranEvaluator::get_llvm2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
    Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager,
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 375, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10184, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 318, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 172, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: subroutine_from_function
```

**Comment by gxyd** [comment]
A program which produces a similar error on *simplifier_pass* branch, not necessarily needed for stdlib compilation though:

### Program
```f90
program main
    implicit none
    logical :: x4(3) = [.true., .false., .true.], y4 = .true.
    print *, findloc(x4, y4, 1)
end program main
```

### Output
```console
> lfortran test.f90
ASR verify pass error: FunctionCall::m_name _lcompilers_findloc must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: intrinsic_function
```

**Comment by Pranavchiku** [comment]
This is tricky, it fails even in main means not the exact MRE for stdlib.

**Comment by gxyd** [comment]
> ```fortran
> subroutine test_diag_int16()
> integer, parameter :: n = 4
> integer :: a(n, n), e(n,n)
> e = diag1(diag(a))
> contains
> function diag(A) result(res)
> integer, intent(in) :: A(:,:)
> integer :: res(minval(shape(A)))
> ! integer :: i
> ! do i = 1, minval(shape(A))
> !     res(i) = A(i,i)
> ! end do
> end function diag
> 
> function diag1(v) result(res)
> integer, intent(in) :: v(:)
> integer :: res(size(v),size(v))
> ! integer :: i
> ! res = 0
> ! do i = 1, size(v)
> !     res(i,i) = v(i)
> ! end do
> end function diag1
> end subroutine test_diag_int16
> ```
> 
> ```
> % lfortran a.f90 --realloc-lhs --show-llvm
> ASR verify pass error: FunctionCall::m_name diag must be returning a non-void value.
> Internal Compiler Error: Unhandled exception
> Traceback (most recent call last):
>   File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2668, in main
>     return main_app(argc, argv);
>   File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2510, in main_app(int, char**)
>     return emit_llvm(arg_file, lfortran_pass_manager,
>   File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 940, in (anonymous namespace)::emit_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::PassManager&, LCompilers::CompilerOptions&)
>     = fe.get_llvm(input, lm, pass_manager, diagnostics);
>   File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 309, in LCompilers::FortranEvaluator::get_llvm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
>     Result<std::unique_ptr<LLVMModule>> res = get_llvm2(code, lm, pass_manager, diagnostics);
>   File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 330, in LCompilers::FortranEvaluator::get_llvm2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, LCompilers::LocationManager&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&)
>     Result<std::unique_ptr<LLVMModule>> res = get_llvm3(*asr.result, pass_manager,
>   File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 375, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
>     = asr_to_llvm(asr, diagnostics,
>   File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10184, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
>     pass_manager.apply_passes(al, &asr, co.po, diagnostics);
>   File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 318, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
>     apply_passes(al, asr, _passes, pass_options, diagnostics);
>   File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 172, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
>     throw LCompilersException("Verify failed in the pass: "
> LCompilersException: Verify failed in the pass: subroutine_from_function
> ```

For this program, I tried running it with our current *main* and *simplifier_pass*:

### Output

```console
$ main_lfortran test.f90 --realloc-lhs --show-llvm
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: subroutine_from_function

$lfortran test.f90 --realloc-lhs --show-llvm
ASR verify pass error: FunctionCall::m_name diag must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: subroutine_from_function
```

where `main_lfortran` is our current *main*

**Comment by Pranavchiku** [comment]
Exactly, this and the above are the ones I get when I try to create MRE. It works for me now on simplifier branch, but still stdlib throws same error. I’ll dig more

**Comment by Pranavchiku** [comment]
@gxyd if you wish to continue, pull stdlib-mre-6 branch from my fork. I’ll continue in the evening.

**Comment by gxyd** [comment]
I see `stdlib-mre-2` and `stdlib-mre-1` but nothing by the name `stdlib-mre-6` here: https://github.com/Pranavchiku/lfortran/branches/all?query=stdlib-mre

**Comment by Pranavchiku** [comment]
Here you go: https://github.com/Pranavchiku/lfortran/tree/stdlib-mre-6

**Comment by Pranavchiku** [comment]
My bad, the MRE is fixed, the new error in stdlib is different.

**Comment by gxyd** [comment]
> My bad, the MRE is fixed, the new error in stdlib is different.

Oh really? What error do you get? Because for me, I still get that same error:
```console
> make -j1

....

[ 30%] Linking Fortran executable test_ascii
[ 30%] Built target test_ascii
[ 30%] Building Fortran object test/io/CMakeFiles/test_loadtxt.dir/test_loadtxt.f90.o
[ 31%] Linking Fortran executable test_loadtxt
[ 31%] Built target test_loadtxt
[ 32%] Building Fortran object test/io/CMakeFiles/test_loadtxt_qp.dir/test_loadtxt_qp.f90.o
[ 32%] Linking Fortran executable test_loadtxt_qp
[ 32%] Built target test_loadtxt_qp
[ 32%] Building Fortran object test/io/CMakeFiles/test_savetxt_qp.dir/test_savetxt_qp.f90.o
[ 32%] Linking Fortran executable test_savetxt_qp
[ 33%] Built target test_savetxt_qp
[ 34%] Building Fortran object test/io/CMakeFiles/test_parse_mode.dir/test_parse_mode.f90.o
[ 34%] Linking Fortran executable test_parse_mode
[ 34%] Built target test_parse_mode
[ 35%] Building Fortran object test/linalg/CMakeFiles/test_linalg.dir/test_linalg.f90.o
style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:626:39
    |
626 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:662:39
    |
662 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:698:39
    |
698 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:734:39
    |
734 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:770:39
    |
770 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:806:39
    |
806 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:842:39
    |
842 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/gxyd/OpenSource/lfortran/stdlib/test/linalg/test_linalg.f90:878:39
    |
878 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
ASR verify pass error: FunctionCall::m_name diag_iint16_mat must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: subroutine_from_function
make[2]: *** [test/linalg/CMakeFiles/test_linalg.dir/build.make:79: test/linalg/CMakeFiles/test_linalg.dir/test_linalg.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1688: test/linalg/CMakeFiles/test_linalg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Pranavchiku** [comment]
```console
% git clean -dfx
% git restore --staged .
% git restore .
% FC=lfortran cmake . -DTEST_DRIVE_BUILD_TESTING=OFF -DBUILD_EXAMPLE=ON -DCMAKE_Fortran_COMPILER_WORKS=TRUE -DCMAKE_Fortran_FLAGS="--cpp --realloc-lhs" && make -j
....
[ 34%] Generating test_linalg.f90
[ 35%] Building Fortran object test/linalg/CMakeFiles/test_linalg.dir/test_linalg.f90.o
style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:626:39
    |
626 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:662:39
    |
662 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:698:39
    |
698 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:734:39
    |
734 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:770:39
    |
770 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:806:39
    |
806 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:842:39
    |
842 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='

style suggestion: Use '<=' instead of '.le.'
   --> /Users/pranavchiku/repos/stdlib/test/linalg/test_linalg.f90:878:39
    |
878 |       call check(error, all(abs(diff) .le. abs(tol)), "all(abs(diff) .le. abs(tol)) failed")
    |                                       ^^^^ help: write this as '<='


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
ASR verify pass error: Old physical type conflicts with the physical type of argument 1 0
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2668, in main
    return main_app(argc, argv);
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2567, in main_app(int, char**)
    return compile_src_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 1042, in (anonymous namespace)::compile_src_to_object_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, LCompilers::CompilerOptions&, LCompilers::PassManager&)
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 375, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    = asr_to_llvm(asr, diagnostics,
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10206, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 318, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 172, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: simplifier
make[2]: *** [test/linalg/CMakeFiles/test_linalg.dir/build.make:79: test/linalg/CMakeFiles/test_linalg.dir/test_linalg.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1688: test/linalg/CMakeFiles/test_linalg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by gxyd** [comment]
Interesting, I'm on macOS m1, and I tried a new clone of stdlib as well. I still get:
```console
Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
ASR verify pass error: FunctionCall::m_name diag_iint16_mat must be returning a non-void value.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: subroutine_from_function
make[2]: *** [test/linalg/CMakeFiles/test_linalg.dir/build.make:79: test/linalg/CMakeFiles/test_linalg.dir/test_linalg.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1688: test/linalg/CMakeFiles/test_linalg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

error. I made sure that I've the latest changes for *simplifier_pass* branch.

**Comment by Pranavchiku** [comment]
No, I am in `stdlib-mre-6` branch and not `simplifier_pass`

**Comment by gxyd** [comment]
Ah alright.

**Comment by gxyd** [comment]
I'm a little doubtful if the program listed here: https://github.com/lfortran/lfortran/issues/5007#issue-2570528177 is actually the MRE for issue in stdlib, as when I try to execute it with our *current main*, I get the below error:
```console
> ~/O/lfortran simplifier_pass !1 ?11 ❯ main_lfortran -c test.f90 --realloc-lhs --show-llvm
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Verify failed in the pass: subroutine_from_function
```

**Comment by Pranavchiku** [comment]
Haha, I faced it at https://github.com/lfortran/lfortran/issues/5007#issuecomment-2403984759
